FROM node:12.13.0

ARG NODE_ENV="development"

RUN mkdir /server
RUN mkdir -p /var/www/html/images

WORKDIR /server

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3001

CMD npm run prod-cluster
